name: Every 1 Minute Update

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run the scraper
        run: python main.py
      - name: Commit results
        run: |
          set -e
          git config --global user.email "54890927+Gugun09@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          d="$(date --rfc-3339=s)"
          git add --all
          git commit --allow-empty -m "Auto Update $d"
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
